# Generated by Django 3.1.4 on 2021-07-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20210715_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
